[shortcut]
next = "|"
prev = "["
1    = "<ctrl>+1"
2    = "<ctrl>+2"
3    = "<ctrl>+3"
4    = "<ctrl>+4"
5    = "<ctrl>+5"
6    = "<ctrl>+6"
7    = "<ctrl>+7"
8    = "<ctrl>+8"
9    = "<ctrl>+9"

[organizer.1]
app_name = "dofus"
title = "vahor"

[organizer.2]
app_name = "dofus"
title = "riche"

[organizer.3]
app_name = "dofus"
title = "fleche"

[organizer.4]
app_name = "dofus"
title = "pandas"
